### PR TITLE
FIX Remove class conflict

### PR DESCRIPTION
**Pull request by micmania1**
This is to prevent the scenario described in #20. Where Zend_Loader is called it will use the framework version. 

This file remains only to satisfy any require calls.

### CODE REVIEW

**Comment by chillu** [comment]
Hey Marcus, would you be able to merge this please? A bit of a hacky solution, but so is manually including Zend libs in the first place without a centralised autoloader hehe.

**Comment by nyeholt** [comment]
Sorry, missed this initially!

**Comment by mmichelli** [comment]
You have to delete the file, external-content/thirdparty/Zend/Loader.php to fix the issue. 
 Fatal error: Class 'Zend_Loader' not found in  framework/thirdparty/Zend/Translate.php on line 126

**Comment by mandrew** [comment]
+1 for removing the file external-content/thirdparty/Zend/Loader.php as I still get the Zend_Loader error

**Comment by nyeholt** [comment]
Have just pushed this deletion.

**Comment by mmichelli** [comment]
thanks

**Pull request merged**
